{"name": "test_function", "status": "failed", "statusDetails": {"message": "AssertionError: assert [1, 2, 3] == [1, 2, 4]\n  At index 2 diff: 3 != 4\n  Use -v to get the full diff", "trace": "def test_function():\n        def f():\n            return [1, 2, 3]\n    \n>       assert f() == [1, 2, 4]\nE       assert [1, 2, 3] == [1, 2, 4]\nE         At index 2 diff: 3 != 4\nE         Use -v to get the full diff\n\ntests\\test_assertions.py:25: AssertionError"}, "steps": [{"name": "校验结果", "status": "passed", "attachments": [{"name": " f() ", "source": "07733220-a384-46be-b61b-92fd042698aa-attachment.attach"}, {"name": " [1, 2, 4]", "source": "ec00fa06-5706-4a85-825c-58d4c81dc05c-attachment.attach"}], "start": 1593429174038, "stop": 1593429174039}], "start": 1593429174034, "stop": 1593429174040, "uuid": "b00a085e-6c4b-41d9-93f5-bc5ad9f67e1b", "historyId": "f599f259ae9fb5cf4193db6ff14fac8a", "testCaseId": "5e673510bee38a9ab863e61c5f848502", "fullName": "tests.test_assertions#test_function", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_assertions"}, {"name": "host", "value": "PC-20190912OQVB"}, {"name": "thread", "value": "5048-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_assertions"}]}